### ISSUE TITLE
Allow actual google searching.

### ISSUE THREAD

**Issue by ghostslayer989** [ShizukuIchi/winXP#27] opened 2019-04-01 15:28 UTC
Seeing as when you try to use google on Internet Explorer it always says no results found. Also, can it just be google.com not google.com.tw? Seeing as regions can have restricted results.

**Comment by RonnyO** [comment] 2019-04-01 18:54
Duplicate of https://github.com/ShizukuIchi/winXP/issues/12

**Closed** 2019-04-02 06:36 UTC
